In [14]:
import pandas as pd # Data structure for CSV
import re # Regular Expressions
from sklearn.feature_selection import VarianceThreshold
import numpy as np # Numpy need no introduction
from datetime import datetime as dt

the_now = dt.now()
now = the_now.strftime("%Y-%m-%d_%H:%M:%S")

df = pd.read_csv('../dataset/full.csv')
prev_df = pd.read_csv('../dataset/full.csv')
df_columns = df.columns.tolist()
df_cleaned = pd.DataFrame()
prev_df_columns = []

df.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [15]:
def compare_df():    
    if df_cleaned.empty:
        return
    df_cleaned_columns = df_cleaned.columns.tolist()
    prev_df_columns = prev_df.columns.tolist()

    diff_list_total = list(set(df_columns) - set(df_cleaned_columns))
    diff_list = list(list(set(prev_df_columns) - set(df_cleaned_columns)))

    df_columns_count = len(df_columns)
    df_cleaned_columns_count = len(df_cleaned_columns)
    prev_df_columns_count = len(prev_df_columns)

    total_removed_features = df_columns_count - df_cleaned_columns_count
    this_step_removed_features = prev_df_columns_count - df_cleaned_columns_count

    print("Features excluded (in total):")
    print(diff_list_total)
    print('='*50)
    print("Features excluded (this step):")
    print(diff_list)
    print('='*50)
    print("Removed total: " + str(df_columns_count) + " ---> " + str(df_cleaned_columns_count) + " features")
    print("Total feature removal count: " + str(total_removed_features))
    print('='*50)
    print("Removed this step: " + str(prev_df_columns_count) + " ---> " + str(df_cleaned_columns_count) + " features")
    print("Feature removal this step count: " + str(this_step_removed_features))

# Feature extraction/selection

First, we remove features that contain duplicate data to another.

In [16]:
df_cleaned = df.T.drop_duplicates(keep='first').T

df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [17]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['tBodyGyroMag-sma()', 'tGravityAccMag-arCoeff()2', 'tGravityAccMag-std()', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-arCoeff()4', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-min()', 'tGravityAccMag-iqr()', 'tGravityAccMag-entropy()', 'fBodyAccMag-sma()', 'fBodyBodyGyroJerkMag-sma()', 'tGravityAccMag-energy()', 'tGravityAccMag-mean()', 'tBodyAccMag-sma()', 'fBodyBodyGyroMag-sma()', 'tBodyAccJerkMag-sma()', 'tGravityAccMag-max()', 'tGravityAccMag-mad()', 'tGravityAccMag-arCoeff()3', 'tGravityAccMag-sma()', 'tBodyGyroJerkMag-sma()']
==================================================
Features excluded (this step):
['tBodyGyroMag-sma()', 'tGravityAccMag-arCoeff()2', 'tGravityAccMag-std()', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-arCoeff()4', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-min()', 'tGravityAccMag-iqr()', 'tGravityAccMag-entropy()', 'fBodyAccMag-sma()', 'fBodyBodyGyroJerkMag-sma()', 'tGravityAccMag-energy()', 'tGravityAccMag-mean()', 'tBodyAccMag-sma()', 'fBodyBodyGyroMag-sma()', 'tBodyAccJerkMag-sma()', 'tGravityAccMag-max()', 'tGravityAccMag-mad()', 'tGravityAccMag-arCoeff()3', 'tGravityAccMag-sma()', 'tBodyGyroJerkMag-sma()']
==================================================
Removed total: 563 ---> 542 features
Total feature removal count: 21
==================================================
Removed this step: 563 ---> 542 features
Feature removal this step count: 21

563 ---> 542 features

### Then, we consider what type of feature:
In the dataset, we've got two types of recorded data:
- t-* features: Raw time-series signals recorded at 50hz
- f-* features: Signals transformed using Fast Fourier Transform

There are mathematical functions that have been applied to numerous features, and in some cases the "t" and "p" version of these functions yield no new information.

## Gemini breakdown because my dumbass dont know shit about physics:

### What you can safely remove:
f*-mean():
This function calculates the plain arithmetic mean of the Fourier amplitudes across all frequency bins. For primary acceleration, this is mathematically tied to the baseline time-domain average (tBodyAcc-mean()) or overall signal power. Dropping these across the board will cause almost zero loss in model accuracy because the time-domain equivalent (t) already captures the signal's overall magnitude

f*.max() + f*.min():
Why f is redundant/invalid: In the time domain, tBodyAcc-max()-X tells you the maximum G-force impulse experienced during a movement step. In the frequency domain, fBodyAcc-max()-X simply tells you the amplitude of the single strongest frequency peak. While peak frequency amplitude is informative, peak frequency intensity is already captured far more comprehensively by fBodyAcc-maxFreqInd (index of peak frequency) or fBodyAcc-energy()

f*.std() + f*.iqr() + f*.energy():
Why f is redundant/invalid: Thanks to Parseval’s Theorem, the total energy (variance) of a signal in the time domain is mathematically equal to the total energy of the signal in the frequency domain. Calculating dispersion statistics like std() or iqr() on the time signal tBodyAcc directly measures movement volatility. Doing the exact same calculation on the FFT bins (fBodyAcc-std()) simply measures how spread out the frequency amplitudes are, which strongly co-varies with time-domain variance.

Source for Parseval's Theorem and its valid application in sensory data feature extraction: 
 10.1109/access.2020.2996576

In [18]:
total_features = df_cleaned.columns.tolist()

# Let's remove all f*-mean():
regex = r"^f.*-mean\(\)"
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

# Remove all f*-max():
regex = r"^f.*-max\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

# Remove all f*-min():
regex = r"^f.*-min\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)

df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [19]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['fBodyGyro-min()-X', 'fBodyAccJerk-min()-Y', 'tBodyGyroMag-sma()', 'fBodyAccJerk-max()-X', 'fBodyBodyGyroJerkMag-min()', 'fBodyAccJerk-mean()-Y', 'fBodyAccMag-max()', 'tGravityAccMag-arCoeff()2', 'fBodyGyro-min()-Y', 'tGravityAccMag-std()', 'fBodyAccJerk-mean()-X', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-arCoeff()4', 'fBodyBodyAccJerkMag-sma()', 'fBodyAccMag-mean()', 'tGravityAccMag-min()', 'tGravityAccMag-iqr()', 'fBodyBodyGyroMag-max()', 'tGravityAccMag-entropy()', 'fBodyAccMag-sma()', 'fBodyAcc-mean()-Z', 'fBodyAccJerk-max()-Y', 'fBodyBodyGyroJerkMag-sma()', 'tGravityAccMag-energy()', 'fBodyBodyGyroJerkMag-max()', 'tGravityAccMag-mean()', 'fBodyGyro-max()-X', 'fBodyAcc-min()-Z', 'fBodyGyro-mean()-Y', 'fBodyAcc-max()-Z', 'fBodyBodyAccJerkMag-mean()', 'fBodyAcc-mean()-X', 'fBodyAccJerk-max()-Z', 'tBodyAccMag-sma()', 'fBodyAcc-max()-Y', 'fBodyGyro-min()-Z', 'fBodyAccMag-min()', 'fBodyBodyGyroMag-sma()', 'fBodyBodyAccJerkMag-max()', 'tBodyAccJerkMag-sma()', 'fBodyAcc-mean()-Y', 'fBodyGyro-mean()-X', 'fBodyGyro-max()-Y', 'tGravityAccMag-max()', 'fBodyBodyAccJerkMag-min()', 'fBodyAcc-min()-X', 'fBodyBodyGyroMag-mean()', 'fBodyBodyGyroMag-min()', 'tGravityAccMag-mad()', 'fBodyAccJerk-min()-Z', 'fBodyAcc-max()-X', 'tGravityAccMag-arCoeff()3', 'fBodyAcc-min()-Y', 'fBodyAccJerk-mean()-Z', 'fBodyGyro-mean()-Z', 'fBodyGyro-max()-Z', 'fBodyAccJerk-min()-X', 'fBodyBodyGyroJerkMag-mean()', 'tGravityAccMag-sma()', 'tBodyGyroJerkMag-sma()']
==================================================
Features excluded (this step):
['fBodyGyro-min()-X', 'fBodyAccJerk-min()-Y', 'fBodyAccJerk-max()-X', 'fBodyBodyGyroJerkMag-min()', 'fBodyAccJerk-mean()-Y', 'fBodyAccMag-max()', 'fBodyGyro-min()-Y', 'fBodyAccJerk-mean()-X', 'fBodyAccMag-mean()', 'fBodyBodyGyroMag-max()', 'fBodyAcc-mean()-Z', 'fBodyAccJerk-max()-Y', 'fBodyBodyGyroJerkMag-max()', 'fBodyGyro-max()-X', 'fBodyAcc-min()-Z', 'fBodyGyro-mean()-Y', 'fBodyAcc-max()-Z', 'fBodyBodyAccJerkMag-mean()', 'fBodyAcc-mean()-X', 'fBodyAccJerk-max()-Z', 'fBodyGyro-min()-Z', 'fBodyAcc-max()-Y', 'fBodyAccMag-min()', 'fBodyBodyAccJerkMag-max()', 'fBodyAcc-mean()-Y', 'fBodyGyro-max()-Y', 'fBodyAccJerk-min()-Z', 'fBodyAcc-min()-X', 'fBodyBodyGyroMag-mean()', 'fBodyBodyGyroMag-min()', 'fBodyAcc-max()-X', 'fBodyAcc-min()-Y', 'fBodyAccJerk-mean()-Z', 'fBodyGyro-mean()-Z', 'fBodyGyro-max()-Z', 'fBodyAccJerk-min()-X', 'fBodyBodyGyroJerkMag-mean()', 'fBodyGyro-mean()-X', 'fBodyBodyAccJerkMag-min()']
==================================================
Removed total: 563 ---> 503 features
Total feature removal count: 60
==================================================
Removed this step: 542 ---> 503 features
Feature removal this step count: 39

542 ---> 503 features

In [20]:
# Remove all f*"-energy" (excluding bandsEnergy)
regex = r"^f.*-energy\(\)"
features_to_remove = []
features_to_remove = [i for i in total_features if re.search(regex, i)]
df_cleaned = df_cleaned.drop(columns=features_to_remove)
df_cleaned.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.12352,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.01657,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [21]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['fBodyGyro-min()-X', 'fBodyAccJerk-min()-Y', 'tBodyGyroMag-sma()', 'fBodyGyro-energy()-Y', 'fBodyAccJerk-max()-X', 'fBodyGyro-energy()-Z', 'fBodyBodyGyroJerkMag-min()', 'fBodyAccJerk-mean()-Y', 'fBodyBodyGyroJerkMag-energy()', 'fBodyAccMag-max()', 'fBodyAcc-energy()-Z', 'tGravityAccMag-arCoeff()2', 'fBodyGyro-min()-Y', 'tGravityAccMag-std()', 'fBodyAccJerk-mean()-X', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-arCoeff()4', 'fBodyBodyAccJerkMag-energy()', 'fBodyBodyAccJerkMag-sma()', 'fBodyAccMag-mean()', 'tGravityAccMag-min()', 'tGravityAccMag-iqr()', 'fBodyBodyGyroMag-max()', 'tGravityAccMag-entropy()', 'fBodyAccMag-sma()', 'fBodyAcc-mean()-Z', 'fBodyAccJerk-max()-Y', 'fBodyBodyGyroJerkMag-sma()', 'tGravityAccMag-energy()', 'fBodyBodyGyroJerkMag-max()', 'tGravityAccMag-mean()', 'fBodyGyro-max()-X', 'fBodyAcc-min()-Z', 'fBodyAccJerk-energy()-Y', 'fBodyGyro-mean()-Y', 'fBodyAcc-max()-Z', 'fBodyAccMag-energy()', 'fBodyBodyAccJerkMag-mean()', 'fBodyAcc-mean()-X', 'fBodyAccJerk-max()-Z', 'tBodyAccMag-sma()', 'fBodyAcc-max()-Y', 'fBodyGyro-min()-Z', 'fBodyAccMag-min()', 'fBodyBodyGyroMag-sma()', 'fBodyBodyAccJerkMag-max()', 'fBodyAcc-energy()-X', 'tBodyAccJerkMag-sma()', 'fBodyAcc-mean()-Y', 'fBodyGyro-mean()-X', 'fBodyGyro-max()-Y', 'tGravityAccMag-max()', 'fBodyBodyAccJerkMag-min()', 'fBodyAcc-min()-X', 'fBodyBodyGyroMag-mean()', 'fBodyAccJerk-energy()-X', 'tGravityAccMag-mad()', 'fBodyBodyGyroMag-min()', 'fBodyAcc-energy()-Y', 'fBodyAccJerk-min()-Z', 'fBodyAcc-max()-X', 'tGravityAccMag-arCoeff()3', 'fBodyBodyGyroMag-energy()', 'fBodyAcc-min()-Y', 'fBodyAccJerk-energy()-Z', 'fBodyAccJerk-mean()-Z', 'fBodyGyro-mean()-Z', 'fBodyGyro-max()-Z', 'fBodyAccJerk-min()-X', 'fBodyBodyGyroJerkMag-mean()', 'fBodyGyro-energy()-X', 'tGravityAccMag-sma()', 'tBodyGyroJerkMag-sma()']
==================================================
Features excluded (this step):
['fBodyBodyAccJerkMag-energy()', 'fBodyAccMag-energy()', 'fBodyGyro-energy()-Y', 'fBodyBodyGyroMag-energy()', 'fBodyAccJerk-energy()-Z', 'fBodyGyro-energy()-Z', 'fBodyAcc-energy()-X', 'fBodyBodyGyroJerkMag-energy()', 'fBodyAcc-energy()-Z', 'fBodyGyro-energy()-X', 'fBodyAccJerk-energy()-Y', 'fBodyAccJerk-energy()-X', 'fBodyAcc-energy()-Y']
==================================================
Removed total: 563 ---> 490 features
Total feature removal count: 73
==================================================
Removed this step: 503 ---> 490 features
Feature removal this step count: 13

542 ---> 490 features

# Variance filtering

We are to drop features that have x % sharing of same values.

In [22]:
# We exclude 'subject' and 'Activity':
df_cleaned_no_categorical = df_cleaned.drop(columns=['Activity', 'subject'])

# We'll start easy: 1%.
selector = VarianceThreshold(threshold=0.01)
selector.fit(df_cleaned_no_categorical)

features_to_keep = df_cleaned_no_categorical.columns[selector.get_support()]

df_cleaned = df_cleaned[features_to_keep]

df_cleaned.head()

,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,tBodyAcc-max()-Y,tBodyAcc-max()-Z,tBodyAcc-min()-X,...,fBodyBodyGyroJerkMag-meanFreq(),fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)"
0,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,-0.567378,-0.744413,0.852947,...,-0.074323,-0.298676,-0.710304,-0.112754,0.0304,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,-0.998245,-0.9753,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,-0.557851,-0.818409,0.849308,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,-0.99538,-0.967187,-0.978944,-0.99652,-0.963668,-0.977469,-0.938692,-0.557851,-0.818409,0.843609,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,-0.996091,-0.983403,-0.990675,-0.997099,-0.98275,-0.989302,-0.938692,-0.576159,-0.829711,0.843609,...,0.404573,-0.11729,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,-0.569174,-0.824705,0.849095,...,0.087753,-0.351471,-0.699205,0.12332,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892

In [23]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['fBodyAccJerk-min()-Y', 'fBodyAccJerk-bandsEnergy()-57,64', 'fBodyAccJerk-bandsEnergy()-33,48.2', 'fBodyAcc-energy()-Z', 'fBodyAccJerk-mean()-X', 'fBodyAccJerk-bandsEnergy()-25,32.2', 'fBodyGyro-bandsEnergy()-25,48.1', 'fBodyAccJerk-bandsEnergy()-57,64.1', 'tGravityAccMag-energy()', 'tGravityAcc-std()-Y', 'fBodyAcc-bandsEnergy()-33,40.2', 'fBodyGyro-bandsEnergy()-25,32.1', 'fBodyBodyGyroJerkMag-max()', 'fBodyAcc-min()-Z', 'fBodyAccJerk-energy()-Y', 'fBodyAccJerk-max()-Z', 'fBodyAccMag-min()', 'tBodyAccJerkMag-sma()', 'tBodyAcc-mean()-Y', 'fBodyAccJerk-min()-Z', 'fBodyAcc-min()-X', 'fBodyBodyGyroMag-mean()', 'fBodyGyro-bandsEnergy()-41,48.1', 'Activity', 'fBodyBodyGyroMag-energy()', 'fBodyAccJerk-energy()-Z', 'fBodyAccJerk-min()-X', 'fBodyGyro-min()-X', 'tGravityAcc-mad()-X', 'tBodyGyroMag-sma()', 'fBodyAccJerk-bandsEnergy()-57,64.2', 'tGravityAcc-iqr()-Y', 'tGravityAcc-iqr()-X', 'fBodyAccJerk-mean()-Y', 'fBodyBodyGyroJerkMag-energy()', 'fBodyAccMag-max()', 'fBodyGyro-bandsEnergy()-33,40.1', 'tGravityAccMag-arCoeff()2', 'fBodyGyro-min()-Y', 'tGravityAccMag-std()', 'tGravityAcc-iqr()-Z', 'tBodyAcc-mean()-Z', 'tGravityAccMag-arCoeff()1', 'tGravityAccMag-iqr()', 'fBodyBodyGyroMag-max()', 'fBodyGyro-bandsEnergy()-57,64.1', 'fBodyBodyGyroJerkMag-sma()', 'fBodyAccMag-energy()', 'fBodyBodyAccJerkMag-mean()', 'tBodyAccMag-sma()', 'fBodyAcc-max()-Y', 'fBodyBodyAccJerkMag-max()', 'fBodyAcc-energy()-X', 'fBodyGyro-bandsEnergy()-25,32.2', 'fBodyGyro-bandsEnergy()-49,64.2', 'fBodyGyro-bandsEnergy()-49,56', 'fBodyAccJerk-mean()-Z', 'fBodyGyro-mean()-Z', 'fBodyBodyGyroJerkMag-mean()', 'tGravityAccMag-sma()', 'fBodyBodyAccJerkMag-min()', 'tBodyGyroJerkMag-sma()', 'fBodyGyro-energy()-Y', 'fBodyGyro-bandsEnergy()-25,48.2', 'fBodyAccJerk-max()-X', 'fBodyGyro-energy()-Z', 'fBodyBodyGyroJerkMag-min()', 'tGravityAccMag-arCoeff()4', 'fBodyBodyAccJerkMag-energy()', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-min()', 'tGravityAccMag-entropy()', 'fBodyAcc-mean()-Z', 'fBodyGyro-bandsEnergy()-33,48.2', 'fBodyAccJerk-max()-Y', 'fBodyAccJerk-bandsEnergy()-25,48.2', 'fBodyGyro-min()-Z', 'fBodyAcc-bandsEnergy()-33,48.2', 'fBodyBodyGyroMag-sma()', 'fBodyAcc-bandsEnergy()-25,32.2', 'fBodyGyro-max()-Y', 'tGravityAccMag-max()', 'fBodyAccJerk-energy()-X', 'fBodyGyro-bandsEnergy()-57,64', 'fBodyAcc-min()-Y', 'fBodyGyro-max()-Z', 'fBodyGyro-energy()-X', 'fBodyGyro-bandsEnergy()-57,64.2', 'fBodyGyro-bandsEnergy()-25,32', 'fBodyAcc-bandsEnergy()-25,48.2', 'tBodyAcc-mean()-X', 'tGravityAcc-mad()-Y', 'fBodyAccMag-mean()', 'fBodyAccMag-sma()', 'fBodyGyro-bandsEnergy()-33,48.1', 'tGravityAcc-std()-X', 'tGravityAccMag-mean()', 'fBodyGyro-max()-X', 'fBodyGyro-mean()-Y', 'fBodyAcc-max()-Z', 'fBodyGyro-bandsEnergy()-49,64', 'fBodyAcc-mean()-X', 'fBodyGyro-bandsEnergy()-41,48', 'fBodyAcc-mean()-Y', 'fBodyBodyGyroMag-min()', 'fBodyGyro-bandsEnergy()-33,40.2', 'tGravityAccMag-mad()', 'fBodyAcc-energy()-Y', 'fBodyGyro-bandsEnergy()-41,48.2', 'fBodyAcc-max()-X', 'tGravityAccMag-arCoeff()3', 'fBodyGyro-bandsEnergy()-25,48', 'fBodyAccJerk-bandsEnergy()-33,40.2', 'subject', 'fBodyGyro-mean()-X']
==================================================
Features excluded (this step):
['tGravityAcc-mad()-X', 'fBodyAccJerk-bandsEnergy()-57,64', 'fBodyGyro-bandsEnergy()-57,64.2', 'fBodyAccJerk-bandsEnergy()-57,64.2', 'fBodyGyro-bandsEnergy()-25,48.2', 'fBodyAccJerk-bandsEnergy()-33,48.2', 'tGravityAcc-iqr()-Y', 'tGravityAcc-iqr()-X', 'fBodyGyro-bandsEnergy()-25,32', 'fBodyGyro-bandsEnergy()-33,40.1', 'fBodyAcc-bandsEnergy()-25,48.2', 'tGravityAcc-iqr()-Z', 'tBodyAcc-mean()-Z', 'tBodyAcc-mean()-X', 'tGravityAcc-mad()-Y', 'fBodyAccJerk-bandsEnergy()-25,32.2', 'fBodyGyro-bandsEnergy()-33,48.1', 'tGravityAcc-std()-X', 'fBodyGyro-bandsEnergy()-25,48.1', 'fBodyAccJerk-bandsEnergy()-57,64.1', 'fBodyGyro-bandsEnergy()-57,64.1', 'fBodyGyro-bandsEnergy()-33,48.2', 'fBodyAccJerk-bandsEnergy()-25,48.2', 'tGravityAcc-std()-Y', 'fBodyAcc-bandsEnergy()-33,40.2', 'fBodyGyro-bandsEnergy()-25,32.1', 'fBodyGyro-bandsEnergy()-49,64', 'fBodyGyro-bandsEnergy()-41,48', 'fBodyAcc-bandsEnergy()-33,48.2', 'fBodyGyro-bandsEnergy()-25,32.2', 'fBodyAcc-bandsEnergy()-25,32.2', 'tBodyAcc-mean()-Y', 'fBodyGyro-bandsEnergy()-33,40.2', 'fBodyGyro-bandsEnergy()-57,64', 'fBodyGyro-bandsEnergy()-41,48.2', 'fBodyGyro-bandsEnergy()-41,48.1', 'Activity', 'fBodyGyro-bandsEnergy()-49,64.2', 'fBodyGyro-bandsEnergy()-49,56', 'fBodyGyro-bandsEnergy()-25,48', 'fBodyAccJerk-bandsEnergy()-33,40.2', 'subject']
==================================================
Removed total: 563 ---> 448 features
Total feature removal count: 115
==================================================
Removed this step: 490 ---> 448 features
Feature removal this step count: 42

### Working against multicollinearity
But if two features apply to this, which one to drop? We use Target-Aware Correlation Dropping:

In [24]:
threshold = 0.95

corr_matrix = df_cleaned.corr().abs()

# These two segments are Gemini-generated:

# Extract upper triangle of correlation matrix (excluding diagonal)
upper_tri = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

# Find features with correlation higher than threshold
to_drop = [
    column
    for column in upper_tri.columns
    if any(upper_tri[column] > threshold)
]

df_cleaned = df_cleaned.drop(columns = to_drop)

In [25]:
compare_df()
prev_df = df_cleaned

Features excluded (in total):
['fBodyAccMag-mad()', 'fBodyBodyAccJerkMag-iqr()', 'fBodyBodyGyroMag-entropy()', 'tBodyGyro-iqr()-X', 'fBodyAccJerk-bandsEnergy()-49,64', 'fBodyAccJerk-entropy()-Z', 'fBodyAccJerk-mad()-Y', 'fBodyAccJerk-bandsEnergy()-17,24.1', 'fBodyAccJerk-bandsEnergy()-57,64.1', 'fBodyBodyGyroJerkMag-iqr()', 'fBodyAccMag-min()', 'fBodyAcc-min()-X', 'tBodyAccMag-energy()', 'Activity', 'tBodyGyro-mad()-X', 'tBodyAcc-min()-X', 'tGravityAcc-mad()-X', 'tBodyGyroMag-sma()', 'fBodyGyro-mad()-Z', 'fBodyAccMag-max()', 'tBodyGyroMag-std()', 'angle(Z,gravityMean)', 'tBodyGyroJerk-mad()-Y', 'angle(X,gravityMean)', 'tBodyGyroJerk-iqr()-Z', 'tBodyGyroJerk-entropy()-Z', 'tBodyAcc-energy()-X', 'fBodyAccJerk-entropy()-X', 'fBodyAccJerk-mad()-Z', 'fBodyAcc-entropy()-Y', 'fBodyAccJerk-entropy()-Y', 'tBodyAcc-mad()-X', 'fBodyAccJerk-mean()-Z', 'tBodyGyroJerk-min()-Y', 'fBodyGyro-mean()-Z', 'fBodyBodyGyroJerkMag-mean()', 'fBodyGyro-bandsEnergy()-25,48.2', 'tGravityAcc-arCoeff()-X,2', 'tBodyGyroJerk-entropy()-Y', 'fBodyAccJerk-max()-X', 'fBodyBodyAccJerkMag-mad()', 'tGravityAcc-max()-X', 'tGravityAcc-arCoeff()-Y,4', 'fBodyAcc-bandsEnergy()-1,16', 'tBodyAcc-mad()-Y', 'tBodyAcc-iqr()-X', 'fBodyAcc-kurtosis()-X', 'fBodyGyro-bandsEnergy()-1,8.2', 'tGravityAccMag-min()', 'fBodyAcc-mean()-Z', 'fBodyAccJerk-max()-Y', 'fBodyAcc-bandsEnergy()-25,32.2', 'fBodyAccJerk-bandsEnergy()-17,24.2', 'tGravityAccMag-max()', 'fBodyGyro-entropy()-Z', 'tGravityAcc-mad()-Z', 'fBodyGyro-bandsEnergy()-57,64', 'fBodyGyro-bandsEnergy()-1,16.2', 'fBodyAccJerk-bandsEnergy()-25,48.1', 'fBodyAcc-min()-Y', 'fBodyGyro-energy()-X', 'fBodyAcc-bandsEnergy()-1,16.2', 'tBodyGyroJerk-mad()-X', 'tBodyAcc-mean()-X', 'fBodyAcc-bandsEnergy()-1,8', 'fBodyBodyGyroMag-std()', 'fBodyGyro-bandsEnergy()-33,48.1', 'fBodyGyro-iqr()-Y', 'fBodyGyro-max()-X', 'fBodyAcc-mean()-X', 'fBodyGyro-bandsEnergy()-41,48', 'fBodyGyro-bandsEnergy()-17,32.1', 'fBodyBodyGyroJerkMag-mad()', 'tGravityAccMag-mad()', 'fBodyAcc-energy()-Y', 'fBodyGyro-bandsEnergy()-41,48.2', 'fBodyGyro-bandsEnergy()-25,48', 'fBodyAccJerk-bandsEnergy()-17,32.1', 'fBodyAccJerk-bandsEnergy()-17,32.2', 'fBodyAcc-entropy()-X', 'fBodyAccJerk-min()-Y', 'tBodyAccJerk-arCoeff()-Y,1', 'fBodyGyro-mad()-X', 'tBodyAccJerk-max()-X', 'tGravityAcc-arCoeff()-Y,2', 'fBodyAccJerk-bandsEnergy()-1,24.1', 'fBodyGyro-bandsEnergy()-25,48.1', 'fBodyAccMag-std()', 'fBodyGyro-sma()', 'fBodyAcc-min()-Z', 'fBodyAccJerk-energy()-Y', 'fBodyAccJerk-bandsEnergy()-33,48.1', 'fBodyAccJerk-bandsEnergy()-17,24', 'tBodyGyroJerkMag-mad()', 'tBodyAccMag-mean()', 'tBodyAccJerk-arCoeff()-Z,1', 'tBodyAcc-mean()-Y', 'fBodyAccJerk-bandsEnergy()-41,48.2', 'tBodyGyroJerk-std()-Z', 'fBodyGyro-std()-Z', 'fBodyGyro-bandsEnergy()-17,32', 'tBodyGyro-iqr()-Y', 'fBodyBodyGyroMag-energy()', 'fBodyGyro-bandsEnergy()-33,48', 'tBodyGyroJerkMag-std()', 'fBodyAccJerk-bandsEnergy()-1,16.2', 'tBodyGyroJerk-sma()', 'fBodyAccJerk-bandsEnergy()-57,64.2', 'fBodyAccJerk-mean()-Y', 'tBodyAccJerk-min()-X', 'tBodyAccJerkMag-std()', 'tBodyGyroJerk-mad()-Z', 'fBodyAccJerk-mad()-X', 'tGravityAccMag-std()', 'tBodyGyroJerk-max()-X', 'fBodyGyro-mad()-Y', 'fBodyGyro-bandsEnergy()-57,64.1', 'fBodyBodyGyroJerkMag-sma()', 'fBodyAccJerk-iqr()-Y', 'fBodyBodyGyroMag-iqr()', 'fBodyBodyAccJerkMag-mean()', 'tBodyAccMag-sma()', 'fBodyAcc-max()-Y', 'fBodyAccJerk-iqr()-X', 'fBodyAcc-energy()-X', 'tGravityAcc-max()-Z', 'fBodyGyro-bandsEnergy()-49,64.2', 'fBodyAccJerk-bandsEnergy()-1,24.2', 'tBodyGyroJerk-arCoeff()-Y,1', 'tGravityAccMag-sma()', 'tGravityAcc-arCoeff()-Z,4', 'tBodyGyroJerkMag-sma()', 'fBodyAcc-mad()-X', 'fBodyAccJerk-bandsEnergy()-25,32.1', 'fBodyGyro-energy()-Z', 'tGravityAccMag-arCoeff()4', 'tBodyGyroJerk-arCoeff()-X,1', 'tBodyGyro-min()-Z', 'fBodyAcc-bandsEnergy()-33,48.2', 'fBodyBodyGyroMag-sma()', 'tBodyAccMag-iqr()', 'fBodyAccJerk-bandsEnergy()-1,16.1', 'tBodyAccJerk-min()-Z', 'fBodyAcc-mad()-Y', 'tBodyGyro-sma()', 'tBodyAccJerk-max()-Y', 'fBodyBodyGyroMag-kurtosis()', 'fBodyAccMag-iqr()', 'tBodyGyroJerkMag-mean()', 'fBodyGyro-bandsEnergy()-1,16', 'tGravityAcc-energy()-X', 'tGravityAcc-mad()-Y', 'fBodyAccMag-mean()', 'tBodyAccJerk-mad()-Y', 'tGravityAccMag-mean()', 'fBodyGyro-mean()-Y', 'fBodyGyro-iqr()-X', 'tBodyAccJerk-entropy()-Z', 'fBodyAcc-mean()-Y', 'angle(Y,gravityMean)', 'tBodyAccJerk-mad()-Z', 'fBodyAccJerk-std()-Y', 'tBodyAccJerkMag-iqr()', 'subject', 'fBodyAcc-bandsEnergy()-17,32.1', 'fBodyAccJerk-bandsEnergy()-33,48.2', 'fBodyAcc-energy()-Z', 'fBodyAcc-bandsEnergy()-25,48', 'fBodyAcc-kurtosis()-Z', 'fBodyGyro-bandsEnergy()-1,24.2', 'tBodyAccJerk-energy()-Y', 'fBodyAccJerk-bandsEnergy()-25,32.2', 'tBodyAccJerkMag-mad()', 'tBodyAccMag-std()', 'tGravityAccMag-energy()', 'tGravityAcc-std()-Y', 'fBodyAcc-bandsEnergy()-33,40.2', 'tBodyAccJerkMag-entropy()', 'fBodyAccJerk-max()-Z', 'tBodyAccJerkMag-sma()', 'tBodyAcc-iqr()-Z', 'fBodyBodyGyroMag-mean()', 'tBodyGyro-max()-Y', 'fBodyAcc-bandsEnergy()-25,48.1', 'tBodyGyroMag-max()', 'fBodyBodyGyroMag-mad()', 'fBodyAccJerk-bandsEnergy()-1,24', 'tBodyAccMag-mad()', 'fBodyBodyAccJerkMag-entropy()', 'fBodyAccJerk-bandsEnergy()-49,64.2', 'fBodyBodyGyroJerkMag-kurtosis()', 'tBodyAccMag-arCoeff()2', 'tGravityAcc-iqr()-X', 'fBodyAccJerk-bandsEnergy()-1,16', 'fBodyGyro-kurtosis()-Y', 'fBodyBodyGyroJerkMag-energy()', 'tBodyAccJerk-iqr()-X', 'tGravityAccMag-arCoeff()2', 'tBodyAccJerk-min()-Y', 'fBodyGyro-min()-Y', 'tBodyAcc-mean()-Z', 'tGravityAccMag-iqr()', 'fBodyBodyGyroMag-max()', 'tBodyAccJerk-iqr()-Y', 'tGravityAcc-max()-Y', 'fBodyGyro-kurtosis()-X', 'fBodyGyro-bandsEnergy()-1,16.1', 'fBodyBodyAccJerkMag-max()', 'fBodyGyro-bandsEnergy()-25,32.2', 'fBodyAcc-std()-Z', 'tBodyGyroJerk-arCoeff()-Z,1', 'fBodyAccJerk-bandsEnergy()-9,16.2', 'tBodyGyroJerkMag-max()', 'fBodyBodyAccJerkMag-min()', 'fBodyGyro-energy()-Y', 'fBodyAcc-iqr()-Z', 'tGravityAcc-min()-Y', 'fBodyBodyGyroJerkMag-min()', 'tBodyAcc-max()-Y', 'fBodyBodyAccJerkMag-energy()', 'fBodyGyro-bandsEnergy()-33,48.2', 'fBodyAccJerk-bandsEnergy()-25,48.2', 'tBodyGyroJerk-iqr()-X', 'fBodyGyro-min()-Z', 'fBodyAcc-mad()-Z', 'tBodyAccJerk-max()-Z', 'tBodyGyroJerk-iqr()-Y', 'tGravityAcc-arCoeff()-X,3', 'fBodyAccMag-kurtosis()', 'tBodyGyroJerkMag-energy()', 'fBodyGyro-entropy()-Y', 'fBodyAccJerk-energy()-X', 'fBodyAcc-bandsEnergy()-33,48.1', 'fBodyGyro-std()-X', 'fBodyAccJerk-bandsEnergy()-17,32', 'fBodyGyro-max()-Z', 'tBodyGyro-iqr()-Z', 'tGravityAcc-arCoeff()-Z,2', 'tBodyAccJerk-mad()-X', 'fBodyAcc-std()-X', 'tBodyAcc-min()-Y', 'fBodyGyro-bandsEnergy()-25,32', 'tBodyAccJerkMag-max()', 'tBodyAccJerk-std()-X', 'tBodyGyroJerk-max()-Z', 'fBodyGyro-bandsEnergy()-1,24', 'tBodyAcc-iqr()-Y', 'fBodyGyro-std()-Y', 'fBodyAcc-std()-Y', 'fBodyAccJerk-bandsEnergy()-25,32', 'fBodyAcc-max()-Z', 'fBodyGyro-bandsEnergy()-49,64', 'fBodyAccJerk-std()-Z', 'fBodyBodyGyroMag-min()', 'fBodyGyro-bandsEnergy()-33,40.2', 'fBodyAcc-iqr()-X', 'fBodyAccJerk-bandsEnergy()-1,8', 'tBodyGyroJerk-min()-X', 'fBodyGyro-mean()-X', 'fBodyBodyGyroJerkMag-std()', 'fBodyAcc-bandsEnergy()-33,48', 'fBodyAcc-bandsEnergy()-49,64', 'fBodyAccJerk-bandsEnergy()-57,64', 'fBodyGyro-iqr()-Z', 'fBodyGyro-kurtosis()-Z', 'fBodyAcc-bandsEnergy()-1,16.1', 'fBodyAccJerk-mean()-X', 'fBodyGyro-bandsEnergy()-17,32.2', 'fBodyGyro-bandsEnergy()-25,32.1', 'fBodyBodyGyroJerkMag-max()', 'tGravityAcc-min()-Z', 'fBodyAcc-iqr()-Y', 'fBodyAcc-entropy()-Z', 'fBodyAccJerk-min()-Z', 'fBodyGyro-bandsEnergy()-41,48.1', 'fBodyBodyAccJerkMag-kurtosis()', 'tGravityAcc-min()-X', 'fBodyAccJerk-energy()-Z', 'fBodyAccJerk-min()-X', 'fBodyGyro-min()-X', 'tGravityAcc-arCoeff()-Z,3', 'tGravityAcc-iqr()-Y', 'fBodyAccJerk-bandsEnergy()-49,64.1', 'fBodyAccJerk-iqr()-Z', 'fBodyGyro-bandsEnergy()-33,40.1', 'fBodyGyro-bandsEnergy()-1,24.1', 'tGravityAcc-iqr()-Z', 'tGravityAccMag-arCoeff()1', 'tBodyAccJerk-iqr()-Z', 'tBodyAcc-mad()-Z', 'tBodyGyroJerk-entropy()-X', 'fBodyAccJerk-bandsEnergy()-25,48', 'tBodyGyro-mad()-Z', 'fBodyAccMag-energy()', 'fBodyGyro-bandsEnergy()-49,56', 'tBodyGyro-mad()-Y', 'fBodyAccJerk-bandsEnergy()-9,16', 'tBodyAccMag-entropy()', 'tBodyAccMag-max()', 'fBodyAcc-bandsEnergy()-1,24.1', 'fBodyGyro-bandsEnergy()-49,64.1', 'fBodyBodyGyroJerkMag-entropy()', 'fBodyAcc-bandsEnergy()-1,24.2', 'fBodyAcc-kurtosis()-Y', 'fBodyAccMag-entropy()', 'fBodyBodyAccJerkMag-sma()', 'tGravityAccMag-entropy()', 'fBodyAcc-bandsEnergy()-17,32', 'tBodyAccJerk-arCoeff()-X,1', 'tBodyGyroJerk-std()-X', 'tBodyGyroMag-mean()', 'tBodyGyroJerkMag-iqr()', 'tBodyGyroJerkMag-entropy()', 'fBodyAccJerk-bandsEnergy()-33,48', 'tBodyAcc-max()-X', 'fBodyBodyAccJerkMag-std()', 'fBodyAcc-bandsEnergy()-49,64.2', 'fBodyGyro-max()-Y', 'tBodyGyroJerk-min()-Z', 'tBodyGyroMag-mad()', 'fBodyAcc-bandsEnergy()-1,24', 'tBodyGyroMag-iqr()', 'tBodyAcc-sma()', 'fBodyGyro-bandsEnergy()-57,64.2', 'tGravityAcc-arCoeff()-Y,3', 'fBodyAcc-bandsEnergy()-25,48.2', 'tGravityAcc-arCoeff()-X,4', 'tBodyAccJerkMag-mean()', 'tBodyGyroJerk-max()-Y', 'tBodyAccJerk-std()-Y', 'fBodyAccMag-sma()', 'tGravityAcc-std()-X', 'fBodyAccJerk-sma()', 'fBodyAccJerk-bandsEnergy()-33,40.1', 'fBodyAcc-sma()', 'fBodyAccJerk-std()-X', 'fBodyGyro-entropy()-X', 'fBodyAcc-bandsEnergy()-49,64.1', 'fBodyAcc-max()-X', 'tGravityAccMag-arCoeff()3', 'fBodyAccJerk-bandsEnergy()-9,16.1', 'fBodyAcc-bandsEnergy()-17,32.2', 'tBodyAccJerkMag-energy()', 'fBodyAccJerk-bandsEnergy()-33,40.2', 'tBodyAccJerk-entropy()-Y', 'tBodyAccJerk-sma()']
==================================================
Features excluded (this step):
['fBodyAccMag-mad()', 'fBodyBodyAccJerkMag-iqr()', 'fBodyAcc-bandsEnergy()-49,64', 'fBodyGyro-iqr()-Z', 'fBodyAcc-bandsEnergy()-17,32.1', 'tBodyAccJerk-arCoeff()-Y,1', 'fBodyGyro-kurtosis()-Z', 'fBodyBodyGyroMag-entropy()', 'fBodyAcc-bandsEnergy()-1,16.1', 'tBodyGyro-iqr()-X', 'fBodyGyro-mad()-X', 'fBodyAcc-bandsEnergy()-25,48', 'tBodyAccJerk-max()-X', 'fBodyAccJerk-bandsEnergy()-49,64', 'fBodyAccJerk-entropy()-Z', 'tGravityAcc-arCoeff()-Y,2', 'fBodyAcc-kurtosis()-Z', 'fBodyGyro-bandsEnergy()-1,24.2', 'fBodyAccJerk-mad()-Y', 'fBodyAccJerk-bandsEnergy()-17,24.1', 'fBodyAccJerk-bandsEnergy()-1,24.1', 'tBodyAccJerk-energy()-Y', 'fBodyAccMag-std()', 'tBodyAccJerkMag-mad()', 'tBodyAccMag-std()', 'fBodyGyro-bandsEnergy()-17,32.2', 'fBodyGyro-sma()', 'fBodyAccJerk-bandsEnergy()-33,48.1', 'tBodyAccJerkMag-entropy()', 'fBodyBodyGyroJerkMag-iqr()', 'fBodyAccJerk-bandsEnergy()-17,24', 'tGravityAcc-min()-Z', 'tBodyGyroJerkMag-mad()', 'tBodyAccMag-mean()', 'fBodyAcc-iqr()-Y', 'tBodyAccJerk-arCoeff()-Z,1', 'tBodyAcc-iqr()-Z', 'fBodyAcc-entropy()-Z', 'fBodyAccJerk-bandsEnergy()-41,48.2', 'tBodyAccMag-energy()', 'tBodyGyro-max()-Y', 'tBodyGyroJerk-std()-Z', 'fBodyGyro-std()-Z', 'fBodyGyro-bandsEnergy()-17,32', 'fBodyBodyAccJerkMag-kurtosis()', 'fBodyAcc-bandsEnergy()-25,48.1', 'tGravityAcc-min()-X', 'tBodyGyro-iqr()-Y', 'tBodyGyroMag-max()', 'fBodyBodyGyroMag-mad()', 'fBodyGyro-bandsEnergy()-33,48', 'tBodyGyro-mad()-X', 'tBodyGyroJerkMag-std()', 'fBodyAccJerk-bandsEnergy()-1,24', 'tBodyAccMag-mad()', 'fBodyBodyAccJerkMag-entropy()', 'fBodyAccJerk-bandsEnergy()-49,64.2', 'fBodyAccJerk-bandsEnergy()-1,16.2', 'tBodyAcc-min()-X', 'tBodyGyroJerk-sma()', 'fBodyBodyGyroJerkMag-kurtosis()', 'tBodyAccMag-arCoeff()2', 'fBodyGyro-mad()-Z', 'tGravityAcc-arCoeff()-Z,3', 'fBodyAccJerk-bandsEnergy()-1,16', 'fBodyAccJerk-bandsEnergy()-49,64.1', 'fBodyGyro-kurtosis()-Y', 'tBodyAccJerk-min()-X', 'tBodyAccJerkMag-std()', 'tBodyAccJerk-iqr()-X', 'tBodyGyroMag-std()', 'angle(Z,gravityMean)', 'tBodyGyroJerk-mad()-Z', 'tBodyAccJerk-min()-Y', 'fBodyAccJerk-mad()-X', 'tBodyGyroJerk-mad()-Y', 'fBodyAccJerk-iqr()-Z', 'fBodyGyro-bandsEnergy()-1,24.1', 'tBodyGyroJerk-max()-X', 'angle(X,gravityMean)', 'fBodyGyro-mad()-Y', 'tBodyAccJerk-iqr()-Z', 'tBodyAcc-mad()-Z', 'tBodyGyroJerk-entropy()-X', 'tBodyAccJerk-iqr()-Y', 'tGravityAcc-max()-Y', 'fBodyAccJerk-bandsEnergy()-25,48', 'fBodyAccJerk-iqr()-Y', 'tBodyGyro-mad()-Z', 'fBodyBodyGyroMag-iqr()', 'tBodyGyroJerk-iqr()-Z', 'tBodyGyroJerk-entropy()-Z', 'fBodyGyro-kurtosis()-X', 'tBodyAcc-energy()-X', 'fBodyGyro-bandsEnergy()-1,16.1', 'fBodyAccJerk-entropy()-X', 'fBodyAccJerk-iqr()-X', 'fBodyAccJerk-mad()-Z', 'fBodyAcc-std()-Z', 'tGravityAcc-max()-Z', 'fBodyAcc-entropy()-Y', 'fBodyAccJerk-entropy()-Y', 'tBodyGyroJerk-arCoeff()-Z,1', 'tBodyAcc-mad()-X', 'fBodyAccJerk-bandsEnergy()-1,24.2', 'tBodyGyroJerk-arCoeff()-Y,1', 'tBodyGyro-mad()-Y', 'fBodyAccJerk-bandsEnergy()-9,16', 'fBodyAccJerk-bandsEnergy()-9,16.2', 'tBodyGyroJerk-min()-Y', 'tGravityAcc-arCoeff()-Z,4', 'tBodyGyroJerkMag-max()', 'tBodyAccMag-entropy()', 'fBodyAcc-mad()-X', 'fBodyAcc-iqr()-Z', 'fBodyAccJerk-bandsEnergy()-25,32.1', 'tGravityAcc-arCoeff()-X,2', 'tBodyGyroJerk-entropy()-Y', 'tGravityAcc-min()-Y', 'tBodyAccMag-max()', 'fBodyBodyAccJerkMag-mad()', 'fBodyAcc-bandsEnergy()-1,24.1', 'fBodyGyro-bandsEnergy()-49,64.1', 'tGravityAcc-max()-X', 'tGravityAcc-arCoeff()-Y,4', 'fBodyBodyGyroJerkMag-entropy()', 'fBodyAcc-bandsEnergy()-1,16', 'tBodyAcc-mad()-Y', 'fBodyAcc-bandsEnergy()-1,24.2', 'tBodyAcc-max()-Y', 'fBodyAcc-kurtosis()-Y', 'tBodyAcc-iqr()-X', 'fBodyAcc-kurtosis()-X', 'fBodyGyro-bandsEnergy()-1,8.2', 'fBodyAccMag-entropy()', 'tBodyAccJerk-sma()', 'fBodyAcc-bandsEnergy()-17,32', 'tBodyGyroJerk-iqr()-X', 'tBodyGyroJerk-arCoeff()-X,1', 'tBodyAccJerk-arCoeff()-X,1', 'tBodyGyro-min()-Z', 'tBodyGyroJerk-std()-X', 'fBodyAcc-entropy()-X', 'tBodyGyroMag-mean()', 'fBodyAcc-mad()-Z', 'tBodyGyroJerkMag-iqr()', 'tBodyGyroJerkMag-entropy()', 'tBodyAccJerk-max()-Z', 'tBodyAccMag-iqr()', 'tBodyGyroJerk-iqr()-Y', 'fBodyAccJerk-bandsEnergy()-33,48', 'tGravityAcc-arCoeff()-X,3', 'tBodyAcc-max()-X', 'fBodyBodyAccJerkMag-std()', 'fBodyAcc-bandsEnergy()-49,64.2', 'fBodyAccJerk-bandsEnergy()-1,16.1', 'fBodyAccJerk-bandsEnergy()-17,24.2', 'fBodyGyro-entropy()-Z', 'fBodyAccMag-kurtosis()', 'tBodyGyroJerkMag-energy()', 'fBodyGyro-entropy()-Y', 'tBodyGyroJerk-min()-Z', 'tBodyAccJerk-min()-Z', 'tGravityAcc-mad()-Z', 'fBodyAcc-bandsEnergy()-33,48.1', 'tBodyGyroMag-mad()', 'fBodyGyro-bandsEnergy()-1,16.2', 'fBodyAccJerk-bandsEnergy()-25,48.1', 'fBodyAcc-bandsEnergy()-1,24', 'fBodyGyro-std()-X', 'tBodyGyroMag-iqr()', 'tBodyAcc-sma()', 'fBodyAcc-mad()-Y', 'tBodyGyro-sma()', 'fBodyAccJerk-bandsEnergy()-17,32', 'tBodyAccJerk-max()-Y', 'tBodyGyro-iqr()-Z', 'tGravityAcc-arCoeff()-Z,2', 'fBodyAcc-bandsEnergy()-1,16.2', 'tBodyAccJerk-mad()-X', 'fBodyAcc-std()-X', 'tBodyAcc-min()-Y', 'tGravityAcc-arCoeff()-Y,3', 'tBodyGyroJerk-mad()-X', 'fBodyBodyGyroMag-kurtosis()', 'fBodyAccMag-iqr()', 'tBodyGyroJerkMag-mean()', 'tBodyAccJerkMag-max()', 'fBodyGyro-bandsEnergy()-1,16', 'tGravityAcc-energy()-X', 'tBodyAccJerk-std()-X', 'tBodyGyroJerk-max()-Z', 'fBodyGyro-bandsEnergy()-1,24', 'tGravityAcc-arCoeff()-X,4', 'tBodyAccJerkMag-mean()', 'tBodyGyroJerk-max()-Y', 'tBodyAcc-iqr()-Y', 'fBodyAcc-bandsEnergy()-1,8', 'fBodyGyro-std()-Y', 'fBodyBodyGyroMag-std()', 'tBodyAccJerk-std()-Y', 'fBodyAcc-std()-Y', 'fBodyAccJerk-bandsEnergy()-25,32', 'fBodyAccJerk-sma()', 'tBodyAccJerk-mad()-Y', 'fBodyGyro-iqr()-Y', 'fBodyAccJerk-bandsEnergy()-33,40.1', 'fBodyGyro-bandsEnergy()-17,32.1', 'fBodyAcc-sma()', 'fBodyAccJerk-std()-X', 'fBodyGyro-entropy()-X', 'fBodyAccJerk-std()-Z', 'fBodyGyro-iqr()-X', 'tBodyAccJerk-entropy()-Z', 'fBodyBodyGyroJerkMag-mad()', 'fBodyAcc-bandsEnergy()-49,64.1', 'angle(Y,gravityMean)', 'fBodyAccJerk-bandsEnergy()-9,16.1', 'tBodyAccJerk-mad()-Z', 'fBodyAcc-bandsEnergy()-17,32.2', 'fBodyAccJerk-bandsEnergy()-17,32.1', 'fBodyAccJerk-std()-Y', 'tBodyAccJerkMag-iqr()', 'tBodyAccJerkMag-energy()', 'tBodyAccJerk-entropy()-Y', 'fBodyAcc-iqr()-X', 'fBodyAccJerk-bandsEnergy()-1,8', 'tBodyGyroJerk-min()-X', 'fBodyBodyGyroJerkMag-std()', 'fBodyAcc-bandsEnergy()-33,48', 'fBodyAccJerk-bandsEnergy()-17,32.2']
==================================================
Removed total: 563 ---> 217 features
Total feature removal count: 346
==================================================
Removed this step: 448 ---> 217 features
Feature removal this step count: 231

### Bring back 'Activity' and 'subject'
Let's bring the gang back together babey

In [28]:
print(df_cleaned.columns.tolist())

['tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z', 'tBodyAcc-max()-Z', 'tBodyAcc-min()-Z', 'tBodyAcc-energy()-Y', 'tBodyAcc-energy()-Z', 'tBodyAcc-entropy()-X', 'tBodyAcc-entropy()-Y', 'tBodyAcc-entropy()-Z', 'tBodyAcc-arCoeff()-X,1', 'tBodyAcc-arCoeff()-X,2', 'tBodyAcc-arCoeff()-X,3', 'tBodyAcc-arCoeff()-X,4', 'tBodyAcc-arCoeff()-Y,1', 'tBodyAcc-arCoeff()-Y,2', 'tBodyAcc-arCoeff()-Y,3', 'tBodyAcc-arCoeff()-Y,4', 'tBodyAcc-arCoeff()-Z,1', 'tBodyAcc-arCoeff()-Z,2', 'tBodyAcc-arCoeff()-Z,3', 'tBodyAcc-arCoeff()-Z,4', 'tBodyAcc-correlation()-X,Y', 'tBodyAcc-correlation()-X,Z', 'tBodyAcc-correlation()-Y,Z', 'tGravityAcc-mean()-X', 'tGravityAcc-mean()-Y', 'tGravityAcc-mean()-Z', 'tGravityAcc-std()-Z', 'tGravityAcc-sma()', 'tGravityAcc-energy()-Y', 'tGravityAcc-energy()-Z', 'tGravityAcc-entropy()-X', 'tGravityAcc-entropy()-Y', 'tGravityAcc-entropy()-Z', 'tGravityAcc-arCoeff()-X,1', 'tGravityAcc-arCoeff()-Y,1', 'tGravityAcc-arCoeff()-Z,1', 'tGravityAcc-correlation()-X,Y', 'tGravityAcc-correlation()-X,Z', 'tGravityAcc-correlation()-Y,Z', 'tBodyAccJerk-mean()-X', 'tBodyAccJerk-mean()-Y', 'tBodyAccJerk-mean()-Z', 'tBodyAccJerk-std()-Z', 'tBodyAccJerk-energy()-X', 'tBodyAccJerk-energy()-Z', 'tBodyAccJerk-entropy()-X', 'tBodyAccJerk-arCoeff()-X,2', 'tBodyAccJerk-arCoeff()-X,3', 'tBodyAccJerk-arCoeff()-X,4', 'tBodyAccJerk-arCoeff()-Y,2', 'tBodyAccJerk-arCoeff()-Y,3', 'tBodyAccJerk-arCoeff()-Y,4', 'tBodyAccJerk-arCoeff()-Z,2', 'tBodyAccJerk-arCoeff()-Z,3', 'tBodyAccJerk-arCoeff()-Z,4', 'tBodyAccJerk-correlation()-X,Y', 'tBodyAccJerk-correlation()-X,Z', 'tBodyAccJerk-correlation()-Y,Z', 'tBodyGyro-mean()-X', 'tBodyGyro-mean()-Y', 'tBodyGyro-mean()-Z', 'tBodyGyro-std()-X', 'tBodyGyro-std()-Y', 'tBodyGyro-std()-Z', 'tBodyGyro-max()-X', 'tBodyGyro-max()-Z', 'tBodyGyro-min()-X', 'tBodyGyro-min()-Y', 'tBodyGyro-energy()-X', 'tBodyGyro-energy()-Y', 'tBodyGyro-energy()-Z', 'tBodyGyro-entropy()-X', 'tBodyGyro-entropy()-Y', 'tBodyGyro-entropy()-Z', 'tBodyGyro-arCoeff()-X,1', 'tBodyGyro-arCoeff()-X,2', 'tBodyGyro-arCoeff()-X,3', 'tBodyGyro-arCoeff()-X,4', 'tBodyGyro-arCoeff()-Y,1', 'tBodyGyro-arCoeff()-Y,2', 'tBodyGyro-arCoeff()-Y,3', 'tBodyGyro-arCoeff()-Y,4', 'tBodyGyro-arCoeff()-Z,1', 'tBodyGyro-arCoeff()-Z,2', 'tBodyGyro-arCoeff()-Z,3', 'tBodyGyro-arCoeff()-Z,4', 'tBodyGyro-correlation()-X,Y', 'tBodyGyro-correlation()-X,Z', 'tBodyGyro-correlation()-Y,Z', 'tBodyGyroJerk-mean()-X', 'tBodyGyroJerk-mean()-Y', 'tBodyGyroJerk-mean()-Z', 'tBodyGyroJerk-std()-Y', 'tBodyGyroJerk-energy()-X', 'tBodyGyroJerk-energy()-Y', 'tBodyGyroJerk-energy()-Z', 'tBodyGyroJerk-arCoeff()-X,2', 'tBodyGyroJerk-arCoeff()-X,3', 'tBodyGyroJerk-arCoeff()-X,4', 'tBodyGyroJerk-arCoeff()-Y,2', 'tBodyGyroJerk-arCoeff()-Y,3', 'tBodyGyroJerk-arCoeff()-Y,4', 'tBodyGyroJerk-arCoeff()-Z,2', 'tBodyGyroJerk-arCoeff()-Z,3', 'tBodyGyroJerk-arCoeff()-Z,4', 'tBodyGyroJerk-correlation()-X,Y', 'tBodyGyroJerk-correlation()-X,Z', 'tBodyGyroJerk-correlation()-Y,Z', 'tBodyAccMag-min()', 'tBodyAccMag-arCoeff()1', 'tBodyAccMag-arCoeff()3', 'tBodyAccMag-arCoeff()4', 'tBodyAccJerkMag-min()', 'tBodyAccJerkMag-arCoeff()1', 'tBodyAccJerkMag-arCoeff()2', 'tBodyAccJerkMag-arCoeff()3', 'tBodyAccJerkMag-arCoeff()4', 'tBodyGyroMag-min()', 'tBodyGyroMag-energy()', 'tBodyGyroMag-entropy()', 'tBodyGyroMag-arCoeff()1', 'tBodyGyroMag-arCoeff()2', 'tBodyGyroMag-arCoeff()3', 'tBodyGyroMag-arCoeff()4', 'tBodyGyroJerkMag-min()', 'tBodyGyroJerkMag-arCoeff()1', 'tBodyGyroJerkMag-arCoeff()2', 'tBodyGyroJerkMag-arCoeff()3', 'tBodyGyroJerkMag-arCoeff()4', 'fBodyAcc-maxInds-X', 'fBodyAcc-maxInds-Y', 'fBodyAcc-maxInds-Z', 'fBodyAcc-meanFreq()-X', 'fBodyAcc-meanFreq()-Y', 'fBodyAcc-meanFreq()-Z', 'fBodyAcc-skewness()-X', 'fBodyAcc-skewness()-Y', 'fBodyAcc-skewness()-Z', 'fBodyAcc-bandsEnergy()-9,16', 'fBodyAcc-bandsEnergy()-17,24', 'fBodyAcc-bandsEnergy()-25,32', 'fBodyAcc-bandsEnergy()-33,40', 'fBodyAcc-bandsEnergy()-41,48', 'fBodyAcc-bandsEnergy()-49,56', 'fBodyAcc-bandsEnergy()-57,64', 'fBodyAcc-bandsEnergy()-1,8.1', 'fBodyAcc-bandsEnergy()-9,16.1', 'fBodyAcc-bandsEnergy()-17,24.1', 'fBodyAcc-bandsEnergy()-25,32.1', 'fBodyAcc-bandsEnergy()-33,40.1', 'fBodyAcc-bandsEnergy()-41,48.1', 'fBodyAcc-bandsEnergy()-49,56.1', 'fBodyAcc-bandsEnergy()-57,64.1', 'fBodyAcc-bandsEnergy()-1,8.2', 'fBodyAcc-bandsEnergy()-9,16.2', 'fBodyAcc-bandsEnergy()-17,24.2', 'fBodyAcc-bandsEnergy()-41,48.2', 'fBodyAcc-bandsEnergy()-49,56.2', 'fBodyAcc-bandsEnergy()-57,64.2', 'fBodyAccJerk-maxInds-X', 'fBodyAccJerk-maxInds-Y', 'fBodyAccJerk-maxInds-Z', 'fBodyAccJerk-meanFreq()-X', 'fBodyAccJerk-meanFreq()-Y', 'fBodyAccJerk-meanFreq()-Z', 'fBodyAccJerk-skewness()-X', 'fBodyAccJerk-kurtosis()-X', 'fBodyAccJerk-skewness()-Y', 'fBodyAccJerk-kurtosis()-Y', 'fBodyAccJerk-skewness()-Z', 'fBodyAccJerk-kurtosis()-Z', 'fBodyAccJerk-bandsEnergy()-33,40', 'fBodyAccJerk-bandsEnergy()-41,48', 'fBodyAccJerk-bandsEnergy()-49,56', 'fBodyAccJerk-bandsEnergy()-1,8.1', 'fBodyAccJerk-bandsEnergy()-41,48.1', 'fBodyAccJerk-bandsEnergy()-49,56.1', 'fBodyAccJerk-bandsEnergy()-1,8.2', 'fBodyAccJerk-bandsEnergy()-49,56.2', 'fBodyGyro-maxInds-X', 'fBodyGyro-maxInds-Y', 'fBodyGyro-maxInds-Z', 'fBodyGyro-meanFreq()-X', 'fBodyGyro-meanFreq()-Y', 'fBodyGyro-meanFreq()-Z', 'fBodyGyro-skewness()-X', 'fBodyGyro-skewness()-Y', 'fBodyGyro-skewness()-Z', 'fBodyGyro-bandsEnergy()-1,8', 'fBodyGyro-bandsEnergy()-9,16', 'fBodyGyro-bandsEnergy()-17,24', 'fBodyGyro-bandsEnergy()-33,40', 'fBodyGyro-bandsEnergy()-1,8.1', 'fBodyGyro-bandsEnergy()-9,16.1', 'fBodyGyro-bandsEnergy()-17,24.1', 'fBodyGyro-bandsEnergy()-49,56.1', 'fBodyGyro-bandsEnergy()-9,16.2', 'fBodyGyro-bandsEnergy()-17,24.2', 'fBodyGyro-bandsEnergy()-49,56.2', 'fBodyAccMag-maxInds', 'fBodyAccMag-meanFreq()', 'fBodyAccMag-skewness()', 'fBodyBodyAccJerkMag-maxInds', 'fBodyBodyAccJerkMag-meanFreq()', 'fBodyBodyAccJerkMag-skewness()', 'fBodyBodyGyroMag-maxInds', 'fBodyBodyGyroMag-meanFreq()', 'fBodyBodyGyroMag-skewness()', 'fBodyBodyGyroJerkMag-maxInds', 'fBodyBodyGyroJerkMag-meanFreq()', 'fBodyBodyGyroJerkMag-skewness()', 'angle(tBodyAccMean,gravity)', 'angle(tBodyAccJerkMean),gravityMean)', 'angle(tBodyGyroMean,gravityMean)', 'angle(tBodyGyroJerkMean,gravityMean)']

In [27]:
cleaned_df = pd.concat([df_cleaned, df[['Activity', 'subject']]], axis=1)

# cleaned_df.to_csv(rf'../dataset/full.v3_{now}.csv', index=False)